apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
data:
  app.properties: |
    key1=value1
    key2=value2
  config.json: |
    {
      "settingA": "foo",
      "settingB": "bar"
    }